INSERT INTO courses (course_code, course_title, course_description) VALUES
('CS101', 'Introduction to Computer Science', 'An overview of the fundamentals of computer science, programming, and computational thinking.'),
('MATH201', 'Calculus I', 'Differential and integral calculus of one variable with applications.'),
('PHYS150', 'General Physics I', 'Introduction to mechanics, waves, and thermodynamics with lab component.'),
('CHEM110', 'General Chemistry', 'Covers basic chemical principles and reactions. Designed for science majors.'),
('ENG101', 'English Composition', 'Focuses on improving academic writing skills, including essays and research papers.'),
('BIO120', 'Introduction to Biology', 'An exploration of cellular biology, genetics, evolution, and ecology.'),
('HIST210', 'World History', 'A survey of major civilizations and world events from ancient to modern times.'),
('PSY100', 'Introduction to Psychology', 'Study of human behavior, emotion, cognition, and development.'),
('ART105', 'Fundamentals of Drawing', 'Techniques and practice in drawing using a variety of media.'),
('CS202', 'Data Structures and Algorithms', 'Detailed study of data organization, searching, sorting, and algorithmic problem-solving.'),
('MATH220', 'Linear Algebra', 'Matrices, vector spaces, linear transformations, and eigenvalues.'),
('PHIL101', 'Introduction to Philosophy', 'Critical examination of fundamental questions about knowledge, reality, and morality.'),
('SOC150', 'Introduction to Sociology', 'Study of society, social institutions, and social relationships.'),
('ECON101', 'Principles of Economics', 'Introduction to microeconomics and macroeconomics concepts.'),
('CS303', 'Database Systems', 'Study of database design, SQL, and transaction management.'),
('STAT200', 'Introduction to Statistics', 'Concepts of data collection, analysis, probability, and inference.'),
('MUS100', 'Introduction to Music Theory', 'Study of basic musical elements including melody, harmony, and rhythm.'),
('CS350', 'Operating Systems', 'Concepts of OS design including processes, memory management, and file systems.'),
('ASTR101', 'Introduction to Astronomy', 'Survey of the universe including stars, galaxies, black holes, and cosmology.'),
('ENV200', 'Environmental Science', 'Study of the environment, natural resources, and human impacts on ecosystems.');
